# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

version: "3"

vars:
  D: ""
  RUN: '{{if eq .D ""}}{{else}}echo{{end}}'

tasks:
  detect:
    silent: true
    desc: detect project in current directory
    cmds:
      - |
        export PACKAGES_PATH=$(realpath ./packages)
        export WEB_PATH=$(realpath ./web)
        if [ ! -z {{._path_}} ]; then
          PACKAGES_PATH=$(realpath {{._path_}}/packages)
          WEB_PATH=$(realpath {{._path_}}/web)
        fi

        if [ -d "$PACKAGES_PATH" ] && [ -d "$WEB_PATH" ]; then
          echo "Packages and web directory present."  
          exit 0
        fi

        if [ -d "$PACKAGES_PATH" ]; then
          echo "Packages directory present."
          exit 0
        fi
        if [ -d "$WEB_PATH" ]; then
          echo "Web directory present."
          exit 0
        fi
        die "No project detected (missing packages and web directory)."
  scan:
    silent: true
    desc: scan directory and generate nuvolaris manifest files
    cmds:
      - task: detect
      - |
        export SCAN_PATH=$(realpath ./)
        if [ ! -z {{._path_}} ]; then
          SCAN_PATH=$(realpath {{._path_}})
        fi
        js scanner.js $SCAN_PATH
